version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: isodose_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - python-api

  backend:
    build: ./backend
    container_name: isodose_backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  python-api:
    build: ./python-api
    container_name: isodose_python_api
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./python-api:/app
